version: '3.8'

services:
  # FastAPI
  crewai-api:
    build:
      context: .
      dockerfile: dockerfile.api
    container_name: crewai-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./configs:/app/configs

  # CLI 
  crewai-cli:
    build:
      context: .
      dockerfile: dockerfile.cli
    container_name: crewai-cli
    env_file:
      - .env
    volumes:
      - ./cli:/app/cli
      - ./src:/app/src
      - ./configs:/app/configs
    stdin_open: true
    tty: true