project:
  name: "crew_config"
  description: "crew 설정 정보"

models:
  custom:
    name: "openai/gpt-oss-120b"
    api_base_url: "http://gpurent.kogrobo.com:51089/v1"
    api_key: "14987239852394087234902287"

agents:
  - id: researcher
    role: "AI 뉴스 리서치"
    goal: "AI 에이전트 관련 최신 뉴스를 웹 검색을 통해 수집하고 핵심 정보를 정리한다."
    backstory: |
      최첨단 기술 동향을 누구보다 빠르게 파악하는 전문 리서처
    model: custom
    tools:
      - WebSearchTool

  - id: summary
    role: "AI 뉴스 요약 에이전트"
    goal: "리서치 결과를 짧고 명확하게 요약한다."
    backstory: |
      방대한 데이터를 빠르게 요약하는 데 특화된 전문가.
    model: custom
    tools: []

tasks:
  - id: research_task
    name: "AI 에이전트 관련 뉴스 조사"
    agent: researcher
    description: |
      AI 에이전트와 관련된 최근 뉴스, 트렌드, 기업 동향 등을 웹 검색을 통해 수집하라.
    expected_output: |
      최신 기사 리스트와 핵심 요약 포인트
    
  - id: summary_task
    name: "AI 뉴스 요약"
    agent: summary
    description: |
      리서치 결과를 읽고 핵심 뉴스와 주요 내용을 5~7문장으로 요약하라
    expected_output: |
      주요 뉴스 요약

execution:
  process: sequential
  verbose: true